[profile.default]
src = "src"
test = "test"
via-ir = true
optimizer = true
optimizer_runs = 200

[profile.test]
via-ir = false

[fmt]
number_underscore = "thousands"


[invariant]
runs = 4
depth = 256
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${RPC_URL}"
