[profile.default]
src = "src"
test = "test"
via-ir = true

[profile.test]
via-ir = false

[invariant]
runs = 4
depth = 256
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
