[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
via-ir = true
optimizer = true
optimizer_runs = 1000

[profile.test]
via-ir = false

[fmt]
number_underscore = "thousands"


[invariant]
runs = 200
depth = 256
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${RPC_URL}"